// All tunable game rules live here. Event rule_version remains database-defaulted.
export const XP = {
  photo: 3,
  answer: 5,
  text: 20,
  price: 10,
  listed: 50,
  sold: 80,
  check: 5,
  shipped: 60,
  relisted: 30,
  badge: 100,
  price_drop: 15,
  retake: 10,
  boss: 150,
} as const;
export const levelCurve = { base: 80, perLevel: 40, startingLevel: 1 } as const;
export const titles = [
  [1, "見習い出品者"],
  [3, "駆け出し出品者"],
  [5, "フリマ常連"],
  [8, "目利き出品者"],
  [12, "売れっ子"],
  [16, "フリマ番長"],
] as const;
export const streakMilestones: Record<number, number> = { 3: 10, 7: 30, 14: 60, 30: 150, 100: 500 };
export const gameRules = {
  incompleteTextXp: 10,
  legacyDayStartHour: 4,
  streakRewardTypes: ["badge", "streak", "quest", "boss"],
  restTicketEveryDays: 7,
  maxRestTickets: 3,
  comboWindowMs: 20 * 60 * 1000,
  comboMultipliers: [1, 1, 1.2, 1.5, 2],
  comboCelebrateFrom: 2,
  salesMilestones: [10000, 50000, 100000, 300000, 500000, 1000000],
} as const;
export const caps = { photoPerItem: 6, priceDropPerItemDay: 1, retakePerItemDay: 1 } as const;
export const badgeThresholds = {
  first: 1,
  camera: 30,
  talk: 5,
  combo: 3,
  fire: 7,
  reins: 30,
  sold: 1,
  pack: 5,
  sales100k: 100000,
  ten: 10,
  sales10k: 10000,
  fastMs: 24 * 60 * 60 * 1000,
  priceDrop: 1,
  retake: 1,
  bossSlayer: 1,
  streak7: 7,
} as const;
export const badges = [
  ["first", "badgeFirst", "badgeFirstHint"],
  ["camera", "badgeCamera", "badgeCameraHint"],
  ["talk", "badgeTalk", "badgeTalkHint"],
  ["combo", "badgeCombo", "badgeComboHint"],
  ["fire", "badgeFire", "badgeFireHint"],
  ["reins", "badgeReins", "badgeReinsHint"],
  ["sold", "badgeSold", "badgeSoldHint"],
  ["pack", "badgePack", "badgePackHint"],
  ["100k", "badgeSales", "badgeSalesHint"],
  ["retry", "badgeRetry", "badgeRetryHint"],
  ["ten", "badgeTen", "badgeTenHint"],
  ["sales10k", "badgeSales10k", "badgeSales10kHint"],
  ["fast", "badgeFast", "badgeFastHint"],
  ["priceDrop", "badgePriceDrop", "badgePriceDropHint"],
  ["retake2", "badgeRetake", "badgeRetakeHint"],
  ["bossSlayer", "badgeBossSlayer", "badgeBossSlayerHint"],
  ["streak7", "badgeStreak7", "badgeStreak7Hint"],
] as const;
export const questPool = [
  { id: "list", label: "questList", target: 1, rewardXp: 20 },
  { id: "photo", label: "questPhoto", target: 3, rewardXp: 15 },
  { id: "price", label: "questPrice", target: 1, rewardXp: 15 },
  { id: "bossHit", label: "questBossHit", target: 1, rewardXp: 25 },
  { id: "text", label: "questText", target: 1, rewardXp: 15 },
  { id: "sell", label: "questSell", target: 1, rewardXp: 30 },
] as const;
export const questConfig = { dailyCount: 3 } as const;
export const bossConfig = {
  minimumDays: 3,
  baseHp: 100,
  hpPerDay: 10,
  priceDropDamage: 30,
  retakeDamage: 20,
  hpFloor: 1,
  daysPerLevel: 3,
  fallbackName: "売れ残りボス",
} as const;
export const calendar = { dayMs: 86400000, jstOffsetMs: 9 * 60 * 60 * 1000, weekDays: 7 } as const;
// Adjacent listed/sold tiers stay adjacent at every enabled strength.
export const effectTier = {
  answer: -1,
  photo: -1,
  copy: -1,
  buckle: -1,
  hit: -1,
  quest: 0,
  combo: 0,
  streak: 0,
  shipped: 0,
  badge: 0,
  listed: 1,
  sold: 2,
  bossDefeat: 3,
  levelup: 3,
} as const;
export const effectConfig = {
  tiers: [
    { particles: 30, durationMs: 900, textScale: 1, flash: 0.09, shakePx: 1 },
    { particles: 240, durationMs: 2400, textScale: 1, flash: 0.17, shakePx: 2 },
    { particles: 320, durationMs: 2800, textScale: 1.15, flash: 0.25, shakePx: 4 },
    { particles: 400, durationMs: 3200, textScale: 1.3, flash: 0.33, shakePx: 6 },
  ],
  minorDurationMs: 700,
  vividMultiplier: 1.2,
  maxParticles: 1200,
  particleTailMs: 300,
  particleLifetimeVariation: 0.5,
  shakeDurationMs: 300,
  hitDurationMs: 900,
  reducedFlash: 0.05,
  maxQueue: 12,
  staleSoundMs: 900,
  refreshMs: 30000,
  viewport: { phoneWidth: 480, referenceHeight: 900, maxScale: 2.2, sizeGain: 0.5 },
  colors: ["#F5B301", "#3B4BD8", "#00B8A9", "#FF8FB1", "#FFFFFF"],
  shapes: ["circle", "rectangle", "ribbon", "star"],
} as const;

export const celebrationPriority = {
  bossDefeat: 10,
  quest: 1,
  hit: 1,
  levelup: 9,
  badge: 8,
  sold: 7,
  shipped: 6,
  listed: 5,
  combo: 3,
  streak: 2,
  photo: 1,
  answer: 0,
  copy: 0,
  buckle: 0,
} as const;
export const celebrationSounds = {
  bossDefeat: "sold",
  quest: "check",
  hit: "tap",
  levelup: "levelup",
  badge: "levelup",
  sold: "sold",
  shipped: "ship",
  listed: "pikon",
  combo: "combo",
  streak: "streak",
  photo: "check",
  answer: "tap",
  copy: "check",
  buckle: "buckle",
} as const;
export const celebrationHaptics = {
  quest: [10],
  hit: [10],
  bossDefeat: [20, 40, 20, 40, 80],
  answer: [10],
  photo: [10],
  copy: [12, 40, 12],
  buckle: [8, 30, 20],
  listed: [15, 50, 25],
  shipped: [15, 40, 15, 40, 60],
  sold: [15, 50, 15, 50, 30],
  levelup: [20, 40, 20, 40, 20, 40, 120],
  badge: [20, 40, 20],
  streak: [25, 80, 25],
  combo: [10, 30, 10],
} as const;
